name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: arthur18dev
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Commit and push graphs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/*.svg
          git commit -m "Update pacman graphs" || echo "No changes to commit"
          git push
